### ISSUE TITLE
No registers found

### ISSUE THREAD

**Issue by bdillahu** [gennaro-tedesco/nvim-peekup#2]
I get the window, but no data... not sure how to debug any...

**Comment by gennaro-tedesco** [comment]
This may be related to [this merge request](https://github.com/gennaro-tedesco/nvim-peekup/pull/1). Please update the plugin via `PlugUpdate` (or similar, according to the plugin manager you are using).

Moreover, should the problem persist, please 

- indicate the `neovim --version` you are using 
- show the output of the `:register` command

**Comment by bdillahu** [comment]
That got it, thanks!

**Comment by gennaro-tedesco** [comment]
Great, I am closing the issue then if you consider it solved.
