### ISSUE TITLE
Selected register not copied to default register `"`

### ISSUE THREAD

**Issue by erikw** [gennaro-tedesco/nvim-peekup#27]
Hey,

I would really like to use this plugin. In the past I've used various yang-ring plugins but not been really satisifed. This seems to be a great take on it though!

The problem I have is that when I select a register, it seems like the content is not put in to the default register, so that I can paste it with `p` after selection.

In this video I start with empty registers, copy 3 pieces of texts in to register 1,2 and 3. Then I try to paste by selecting from the dialog `""`, however the selected content is not pasted.

https://user-images.githubusercontent.com/175286/201933216-ae6f27de-ccc5-43a0-b363-d66128286075.mov

## Specs
* Nvim: `v0.8.0` (from Homebrew)
* OS: macOS 12.6
* nvim-peekup:  tip of master branch (69b8e013b26a0f457a213f2285fea00b5635b17d)

Nvim `init.vim`:

```viml
Plug 'gennaro-tedesco/nvim-peekup'
```

**Comment by gennaro-tedesco** [comment]
Good afternoon and thank you for looking into `peekup`!

So, as you can see from [the code](https://github.com/gennaro-tedesco/nvim-peekup/blob/69b8e013b26a0f457a213f2285fea00b5635b17d/lua/nvim-peekup/peekup.lua#L99) all peekup does it moving the selected content into the default register `@` (which is what you are pasting from when executing `p`). It may be that you do not have the default register set to `@`.

1. after selecting the text from the peekup window, execute `"@p` to check what is being pasted: it _must_ be the content you just selected. If this works it means your clipboard settings are different (from the standard ones)
2. what is the output of `set clipboard?`

P. S. I noticed from your recording that there is a problem with the visual selection, it seems the selection doesn't go through the whole word. I will look into it.

**Comment by erikw** [comment]
Thank you @gennaro-tedesco for quick answer!

> 1. after selecting the text from the peekup window, execute `"@p` to check what is being pasted: it _must_ be the content you just selected. If this works it means your clipboard settings are different (from the standard ones)
 
After selecting in the `""` dialog ,`"@p` seems to paste from either register `0` or `1`, not sure.

In the following video:
* Have contents in reg 1,2,3. Reg 1 was the last one I yanked to
* `""` and select reg 3
* `"@p` pasted contents of reg 1
* `p` also pastes content of reg 1

https://user-images.githubusercontent.com/175286/202135740-dfc74b67-2d1b-4545-a165-1c5d85fb441a.mov


I did this a few more times and yes, it seems like the last register that was yanked to is always going to be the register that is being pasted from no matter which was selected in the `""` window

Here's another video:
* Yank to reg 4
* `'''` select reg 7
* `"@p` pastes reg 4
* `""` select reg 7
* `p` pasted reg 4
* 

https://user-images.githubusercontent.com/175286/202136142-ef78290d-897c-4156-a099-427b38a019be.mov



>     2. what is the output of `set clipboard?`
```
clipboard=
```
i.e. it's unset. 

> P. S. I noticed from your recording that there is a problem with the visual selection, it seems the selection doesn't go through the whole word. I will look into it.
Thx!

**Comment by gennaro-tedesco** [comment]
The problem is that you do not have the unnamed register set for your clipboard: do
```
set clipboard+=unnamed
```
and it should work.

However, peekup also gives you the possibility to configure which particular register to use to temporarily store the content you are selecting in the window by amending [this option](https://github.com/gennaro-tedesco/nvim-peekup/blob/69b8e013b26a0f457a213f2285fea00b5635b17d/lua/nvim-peekup/config.lua#L27).

**Comment by erikw** [comment]
Ah `'clipboard'` has default value of `""`. Maybe this should be added to the setup requirements in the README?

Setting `set clipboard+=unnamed` on nvim (Homebrew) macOS has the side-effect of automatically copying everything that goes in to register `*` to the system GUI clipboard. This is not desirable!

However setting

```lua
lua <<EOF
require('nvim-peekup.config').on_keystroke["paste_reg"] = '"'
EOF
```

seems to work so far! The selected register in `""` is now pasted with `p`, without polluting the system clipboard :)

Would it be a better default with `"` instead of `*', so that it works out of the box (at least for macOS users)?

**Comment by gennaro-tedesco** [comment]
> Would it be a better default with " instead of `*', so that it works out of the box (at least for macOS users)?

It could, but I am not sure if it will conflict with other architectures. So far most users do have their clipboard set to `unnamed/unnamedplus`, which is why I initially defaulted to it. I believe the best is still to just expose the variable (independent of the defaults) so that users may understand that it is where the contents are going, and handle it how they find fit.

**Comment by erikw** [comment]
At least it would be good if the README  mention the assumption on `unnamed` as this isn't the default value :)

**Comment by gennaro-tedesco** [comment]
You are right: I have added a line in the README in https://github.com/gennaro-tedesco/nvim-peekup/commit/2e48f2e1ebc198f3624645f13f5ce64d20708272.
