### ISSUE TITLE
Set nowrap

### ISSUE THREAD

**Issue by bdillahu** [gennaro-tedesco/nvim-peekup#3]
May want to consider a way to force the pop up window to “nowrap”... I have my VIM set to normally be wrapped, but that doesn’t work so well in the window.

**Comment by gennaro-tedesco** [comment]
Yes, I agree. I will flag this issue as "feature request" and work on it next.

**Comment by gennaro-tedesco** [comment]
Merged the changes [here](https://github.com/gennaro-tedesco/nvim-peekup/pull/5).

To activate/de-activate wrapping in the popup window simply set
```
lua require('nvim-peekup.config').geometry["wrap"] = false/true
```

**Comment by bdillahu** [comment]
Seems to work fine, thanks!
