### ISSUE TITLE
An option to auto-paste in the buffer the plugin was invoked from

### ISSUE THREAD

**Issue by mfontani** [gennaro-tedesco/nvim-peekup#9]
Rather than having to type `""` then picking the register, then typing `"*p` or `"*P` to paste after or before the current buffer position, allow one or more mappings which instead perform the paste action once the register has been picked.

I'd _ideally_ like to be able to map something like this:

    nnoremap <Leader>P <Plug>PeekupPasteBefore
    nnoremap <Leader>p <Plug>PeekupPasteAfter
    nnoremap "" <Plug>PeekupPaste

... and have the plug-in auto-paste before/after if a register was picked (and for nothing to happen if no registers were picked/if the window was closed/if an invalid key was pressed)

... but I could settle for a way to have a (given as parameter) command executed _on the buffer the plugin was called from_ once a register has been successfully picked and the contents of the `*` register replaced with the contents of the picked register

    nnoremap <Leader>P <Plug>PeekupPaste('"*P')
    nnoremap <Leader>p <Plug>PeekupPaste('"*p')

I've tried to develop this myself but my knowledge of lua is a bit rusty and my knowledge of the neovim API almost nonexistent.

If you've pointers as to how I could find out:

- how to find out which buffer/window/"thing" the plugin's window has been opened from
- how to "hook" on when the plugin's window has been closed, with a successfully picked register

... then I might attempt this, and in that case I'll open a pull-request.

**Comment by gennaro-tedesco** [comment]
This is definitely worth looking into. Without having had much thought on it, one way the following could be done

> how to find out which buffer/window/"thing" the plugin's window has been opened from

can be:

1. either to save the current buffer_id _before_ opening the peekup window (with `bufnr("%")`) and then put the content back into `vim.api.nvim_buf_set_lines(<original buffer>, 0, -1, true, content)`
2. after the peekup window closes the "current buffer" defaults back to what the "previous buffer" was (need to check on this) so one could probably just `put` into the cursor position

> how to "hook" on when the plugin's window has been closed, with a successfully picked register

could you please specify what the desired behaviour should be, here? Would you like the register window to still be available (some sort of buffer hidden or the like)?

**Comment by mfontani** [comment]
> could you please specify what the desired behaviour should be, here?

Overall, I would like to have a mapping which automatically pastes the register name I pick. I'd "obviously" need to choose whether I want to paste before or after, but that's about it.

- I'm in a buffer
- I press a key combination to "pick and paste" above, or "pick and paste" after
- the plugin's buffer opens and I have the option of selecting a buffer
- if I pick a valid register, the register's contents get pasted before or after the position of the cursor on the buffer I invoked the plugin from
- if I don't / if I close the plugin buffer, nothing gets pasted in the buffer I opened the plugin from

To do the above I'd need to get a reference to the buffer the plugin was invoked from, to know on which buffer I should then choose to paste inside of. `bufnr("%")` gets me that. Great, I'll keep that in mind.

Next, I would need to know whether the plugin window selected a buffer. This is currently "kind of" done via `on_keystroke`, but that also does something else. Currently, a byproduct of having selected a buffer is that the contents of the `*` registers have chanced since the plugin was invoked.

Next, I would need to know when the plug-in window was closed. The `floating_window` adds a `<buffer>`-local `BufWipeout` autocommand to wipeout the buffer. I'd likely want to hook there, or "around that point" so I can then perform the logic for something like: "if the user has selected a buffer, paste (before/after) the selected register's contents into that buffer".

> after the peekup window closes the "current buffer" defaults back to what the "previous buffer" was

Yes, that happens, but I cannot seem to find how to perform an action _then_, rather than - say - on the plugin's buffer's "close" action. All I can seem to be able to hook on is "around" the plugin buffer.

With the above changes, the plugin effectively becomes a "pickable register contents paster", which I've so sorely missed :^)

**Comment by gennaro-tedesco** [comment]
I see now, it definitely makes sense. I need to give it some thoughts as it seems to be a little more complicated. 

> Next, I would need to know whether the plugin window selected a buffer. This is currently "kind of" done via on_keystroke, but that also does something else. Currently, a byproduct of having selected a buffer is that the contents of the * registers have chanced since the plugin was invoked.

do you mean "register" here instead of "buffer"? The plugin window selects a register, not a buffer.

> Yes, that happens, but I cannot seem to find how to perform an action then

wouldn't this be just putting into the now-current buffer (usually referred to as 0) [after this line](https://github.com/gennaro-tedesco/nvim-peekup/blob/dde78e4adba0192c3986b20de28d26eca315dec6/lua/nvim-peekup/peekup.lua#L106) (perhaps I am wrong here, I have not checked if it actually works)?

**Comment by mfontani** [comment]
> do you mean "register" here instead of "buffer"?
Yes, sorry!

My lua might be icky, and I've most definitely screwed up the indenting in the source files, but I think https://github.com/mfontani/nvim-peekup/tree/autopaste has it all?
"just" one commit - https://github.com/mfontani/nvim-peekup/commit/2f06faaa768a12bf8971af62c8897fdf9220f56f

With that, all one needs is to:

        nnoremap <Plug>PeekupOpenThenPasteAfter  :lua require('nvim-peekup').peekup_open("p")<CR>
        nnoremap <Plug>PeekupOpenThenPasteBefore :lua require('nvim-peekup').peekup_open("P")<CR>

.. and then *in their own config*:

        nmap <Leader>P <Plug>PeekupOpenThenPasteBefore
        nmap <Leader>p <Plug>PeekupOpenThenPasteAfter

... after which one can:

- use `""` to trigger the usual behaviour the plugin does
- hit `<Leader>P` or `<Leader>p` to paste the contents of the selected register before/after the cursor in the buffer from which they invoked the plugin from.

What's missing is ensuring the picked register is proper...

**Comment by gennaro-tedesco** [comment]
I have had a look at your branch: I have a few suggestions

1. there is no need to carry over the buffer `nr` variable. I could obtain the desired behaviour (namely pasting before/after cursor position) simply doing `vim.cmd('execute "normal! \\"'..key..paste_where..'"')` [here](https://github.com/mfontani/nvim-peekup/commit/2f06faaa768a12bf8971af62c8897fdf9220f56f#r47713736). Unless you feel the need for some other special cases I would say we can get rid of it altogether. This should answer your question of 
> What's missing is ensuring the picked register is proper...

2. I am not sure one must remove the `vim.cmd('let @*=@'..key)` if not `paste_where`: at the end of the day it does not hurt, and if the user wants to use another register we have already dealt with it [here](https://github.com/gennaro-tedesco/nvim-peekup/pull/10).
3. I have noticed that with this change the standard `""` is incredibly slow in opening up. I really do not know what is causing it: `<leader>p`and `<leader>P` open the window at the speed of light (as before): is this happening to you too (or perhaps it is some hidden recursive remapping I have set up somewhere on my machine)?

**Comment by mfontani** [comment]
> I have noticed that with this change the standard "" is incredibly slow in opening up.

I've not experienced that. Could you try the branch in the just-opened issue? It's simpler, works (at least for me) and doesn't pass around a buffer number anymore.

**Comment by gennaro-tedesco** [comment]
This issue was implemented and merged in https://github.com/gennaro-tedesco/nvim-peekup/pull/14
